theme: jekyll-theme-cayman
title: Lakshay Arora
description: Personal Portfolio
locale: en_US
# logo: # filename of a logo image that has been placed into your images directory

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Lakshay Arora
#   avatar: bio-photo.jpg
  bio: "I hope to keep this page updated"
  email: larora@umass.edu
  linkedin: lakshay-arora-8037b1152
  github: lakarora
#   orcid: # ID Number (ex. 0000-0000-0000-0000)
#   researchgate: #username
#   mendeley: #username
#   google:
#     plus: #username
#     analytics:
#     verify:
#     scholar: #id
